name: PowerSchool Revamped
description:
  default: Revamps the PowerSchool interface to be more modern and user-friendly.
namespace: https://grahamsh.com/
version: '1.0.0'
match: 
  - https://*.powerschool.com/guardian/*
  - https://powerschool.*.org/guardian/*
updateURL: https://github.com/GrahamSH-LLK/powerschool/raw/main/dist/bundle.user.js
run-at: document-start